// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MDSecurityLending.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MDSecurityLending_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MDSecurityLending_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ESecurityIDSource.pb.h"
#include "ESecurityType.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MDSecurityLending_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MDSecurityLending_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MDSecurityLending_2eproto;
namespace com {
namespace htsc {
namespace mdc {
namespace insight {
namespace model {
class ADSecurityLendingEntry;
class ADSecurityLendingEntryDefaultTypeInternal;
extern ADSecurityLendingEntryDefaultTypeInternal _ADSecurityLendingEntry_default_instance_;
class ADValidSecurityLendingEntry;
class ADValidSecurityLendingEntryDefaultTypeInternal;
extern ADValidSecurityLendingEntryDefaultTypeInternal _ADValidSecurityLendingEntry_default_instance_;
class MDSecurityLending;
class MDSecurityLendingDefaultTypeInternal;
extern MDSecurityLendingDefaultTypeInternal _MDSecurityLending_default_instance_;
}  // namespace model
}  // namespace insight
}  // namespace mdc
}  // namespace htsc
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* Arena::CreateMaybeMessage<::com::htsc::mdc::insight::model::ADSecurityLendingEntry>(Arena*);
template<> ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* Arena::CreateMaybeMessage<::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry>(Arena*);
template<> ::com::htsc::mdc::insight::model::MDSecurityLending* Arena::CreateMaybeMessage<::com::htsc::mdc::insight::model::MDSecurityLending>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace com {
namespace htsc {
namespace mdc {
namespace insight {
namespace model {

// ===================================================================

class MDSecurityLending :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.htsc.mdc.insight.model.MDSecurityLending) */ {
 public:
  MDSecurityLending();
  virtual ~MDSecurityLending();

  MDSecurityLending(const MDSecurityLending& from);
  MDSecurityLending(MDSecurityLending&& from) noexcept
    : MDSecurityLending() {
    *this = ::std::move(from);
  }

  inline MDSecurityLending& operator=(const MDSecurityLending& from) {
    CopyFrom(from);
    return *this;
  }
  inline MDSecurityLending& operator=(MDSecurityLending&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MDSecurityLending& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MDSecurityLending* internal_default_instance() {
    return reinterpret_cast<const MDSecurityLending*>(
               &_MDSecurityLending_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MDSecurityLending* other);
  friend void swap(MDSecurityLending& a, MDSecurityLending& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MDSecurityLending* New() const final {
    return CreateMaybeMessage<MDSecurityLending>(nullptr);
  }

  MDSecurityLending* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MDSecurityLending>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MDSecurityLending& from);
  void MergeFrom(const MDSecurityLending& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MDSecurityLending* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.htsc.mdc.insight.model.MDSecurityLending";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MDSecurityLending_2eproto);
    return ::descriptor_table_MDSecurityLending_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.htsc.mdc.insight.model.ADValidSecurityLendingEntry ValidBorrows = 27;
  int validborrows_size() const;
  void clear_validborrows();
  static const int kValidBorrowsFieldNumber = 27;
  ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* mutable_validborrows(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >*
      mutable_validborrows();
  const ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry& validborrows(int index) const;
  ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* add_validborrows();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >&
      validborrows() const;

  // repeated .com.htsc.mdc.insight.model.ADValidSecurityLendingEntry ValidALends = 28;
  int validalends_size() const;
  void clear_validalends();
  static const int kValidALendsFieldNumber = 28;
  ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* mutable_validalends(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >*
      mutable_validalends();
  const ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry& validalends(int index) const;
  ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* add_validalends();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >&
      validalends() const;

  // repeated .com.htsc.mdc.insight.model.ADValidSecurityLendingEntry ValidBLends = 29;
  int validblends_size() const;
  void clear_validblends();
  static const int kValidBLendsFieldNumber = 29;
  ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* mutable_validblends(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >*
      mutable_validblends();
  const ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry& validblends(int index) const;
  ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* add_validblends();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >&
      validblends() const;

  // repeated .com.htsc.mdc.insight.model.ADValidSecurityLendingEntry ValidCLends = 30;
  int validclends_size() const;
  void clear_validclends();
  static const int kValidCLendsFieldNumber = 30;
  ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* mutable_validclends(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >*
      mutable_validclends();
  const ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry& validclends(int index) const;
  ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* add_validclends();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >&
      validclends() const;

  // repeated .com.htsc.mdc.insight.model.ADSecurityLendingEntry ALends = 31;
  int alends_size() const;
  void clear_alends();
  static const int kALendsFieldNumber = 31;
  ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* mutable_alends(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >*
      mutable_alends();
  const ::com::htsc::mdc::insight::model::ADSecurityLendingEntry& alends(int index) const;
  ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* add_alends();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >&
      alends() const;

  // repeated .com.htsc.mdc.insight.model.ADSecurityLendingEntry BLends = 32;
  int blends_size() const;
  void clear_blends();
  static const int kBLendsFieldNumber = 32;
  ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* mutable_blends(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >*
      mutable_blends();
  const ::com::htsc::mdc::insight::model::ADSecurityLendingEntry& blends(int index) const;
  ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* add_blends();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >&
      blends() const;

  // repeated .com.htsc.mdc.insight.model.ADSecurityLendingEntry CLends = 33;
  int clends_size() const;
  void clear_clends();
  static const int kCLendsFieldNumber = 33;
  ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* mutable_clends(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >*
      mutable_clends();
  const ::com::htsc::mdc::insight::model::ADSecurityLendingEntry& clends(int index) const;
  ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* add_clends();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >&
      clends() const;

  // repeated .com.htsc.mdc.insight.model.ADValidSecurityLendingEntry ValidReservationBorrows = 34;
  int validreservationborrows_size() const;
  void clear_validreservationborrows();
  static const int kValidReservationBorrowsFieldNumber = 34;
  ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* mutable_validreservationborrows(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >*
      mutable_validreservationborrows();
  const ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry& validreservationborrows(int index) const;
  ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* add_validreservationborrows();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >&
      validreservationborrows() const;

  // repeated .com.htsc.mdc.insight.model.ADValidSecurityLendingEntry ValidReservationLends = 35;
  int validreservationlends_size() const;
  void clear_validreservationlends();
  static const int kValidReservationLendsFieldNumber = 35;
  ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* mutable_validreservationlends(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >*
      mutable_validreservationlends();
  const ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry& validreservationlends(int index) const;
  ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* add_validreservationlends();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >&
      validreservationlends() const;

  // repeated .com.htsc.mdc.insight.model.ADSecurityLendingEntry ReservationBorrows = 36;
  int reservationborrows_size() const;
  void clear_reservationborrows();
  static const int kReservationBorrowsFieldNumber = 36;
  ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* mutable_reservationborrows(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >*
      mutable_reservationborrows();
  const ::com::htsc::mdc::insight::model::ADSecurityLendingEntry& reservationborrows(int index) const;
  ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* add_reservationborrows();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >&
      reservationborrows() const;

  // repeated .com.htsc.mdc.insight.model.ADSecurityLendingEntry ReservationLends = 37;
  int reservationlends_size() const;
  void clear_reservationlends();
  static const int kReservationLendsFieldNumber = 37;
  ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* mutable_reservationlends(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >*
      mutable_reservationlends();
  const ::com::htsc::mdc::insight::model::ADSecurityLendingEntry& reservationlends(int index) const;
  ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* add_reservationlends();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >&
      reservationlends() const;

  // repeated .com.htsc.mdc.insight.model.ADValidSecurityLendingEntry ValidOtcLends = 38;
  int validotclends_size() const;
  void clear_validotclends();
  static const int kValidOtcLendsFieldNumber = 38;
  ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* mutable_validotclends(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >*
      mutable_validotclends();
  const ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry& validotclends(int index) const;
  ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* add_validotclends();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >&
      validotclends() const;

  // string HTSCSecurityID = 1;
  void clear_htscsecurityid();
  static const int kHTSCSecurityIDFieldNumber = 1;
  const std::string& htscsecurityid() const;
  void set_htscsecurityid(const std::string& value);
  void set_htscsecurityid(std::string&& value);
  void set_htscsecurityid(const char* value);
  void set_htscsecurityid(const char* value, size_t size);
  std::string* mutable_htscsecurityid();
  std::string* release_htscsecurityid();
  void set_allocated_htscsecurityid(std::string* htscsecurityid);

  // string TradingPhaseCode = 5;
  void clear_tradingphasecode();
  static const int kTradingPhaseCodeFieldNumber = 5;
  const std::string& tradingphasecode() const;
  void set_tradingphasecode(const std::string& value);
  void set_tradingphasecode(std::string&& value);
  void set_tradingphasecode(const char* value);
  void set_tradingphasecode(const char* value, size_t size);
  std::string* mutable_tradingphasecode();
  std::string* release_tradingphasecode();
  void set_allocated_tradingphasecode(std::string* tradingphasecode);

  // int32 MDDate = 2;
  void clear_mddate();
  static const int kMDDateFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::int32 mddate() const;
  void set_mddate(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 MDTime = 3;
  void clear_mdtime();
  static const int kMDTimeFieldNumber = 3;
  ::PROTOBUF_NAMESPACE_ID::int32 mdtime() const;
  void set_mdtime(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int64 DataTimestamp = 4;
  void clear_datatimestamp();
  static const int kDataTimestampFieldNumber = 4;
  ::PROTOBUF_NAMESPACE_ID::int64 datatimestamp() const;
  void set_datatimestamp(::PROTOBUF_NAMESPACE_ID::int64 value);

  // .com.htsc.mdc.model.ESecurityIDSource securityIDSource = 6;
  void clear_securityidsource();
  static const int kSecurityIDSourceFieldNumber = 6;
  ::com::htsc::mdc::model::ESecurityIDSource securityidsource() const;
  void set_securityidsource(::com::htsc::mdc::model::ESecurityIDSource value);

  // .com.htsc.mdc.model.ESecurityType securityType = 7;
  void clear_securitytype();
  static const int kSecurityTypeFieldNumber = 7;
  ::com::htsc::mdc::model::ESecurityType securitytype() const;
  void set_securitytype(::com::htsc::mdc::model::ESecurityType value);

  // int64 PreWeightedRate = 10;
  void clear_preweightedrate();
  static const int kPreWeightedRateFieldNumber = 10;
  ::PROTOBUF_NAMESPACE_ID::int64 preweightedrate() const;
  void set_preweightedrate(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 PreHighRate = 11;
  void clear_prehighrate();
  static const int kPreHighRateFieldNumber = 11;
  ::PROTOBUF_NAMESPACE_ID::int64 prehighrate() const;
  void set_prehighrate(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 PreLowRate = 12;
  void clear_prelowrate();
  static const int kPreLowRateFieldNumber = 12;
  ::PROTOBUF_NAMESPACE_ID::int64 prelowrate() const;
  void set_prelowrate(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 PreHtscVolume = 13;
  void clear_prehtscvolume();
  static const int kPreHtscVolumeFieldNumber = 13;
  ::PROTOBUF_NAMESPACE_ID::int64 prehtscvolume() const;
  void set_prehtscvolume(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 PreMarketVolume = 14;
  void clear_premarketvolume();
  static const int kPreMarketVolumeFieldNumber = 14;
  ::PROTOBUF_NAMESPACE_ID::int64 premarketvolume() const;
  void set_premarketvolume(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 WeightedRate = 15;
  void clear_weightedrate();
  static const int kWeightedRateFieldNumber = 15;
  ::PROTOBUF_NAMESPACE_ID::int64 weightedrate() const;
  void set_weightedrate(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 HighRate = 16;
  void clear_highrate();
  static const int kHighRateFieldNumber = 16;
  ::PROTOBUF_NAMESPACE_ID::int64 highrate() const;
  void set_highrate(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 LowRate = 17;
  void clear_lowrate();
  static const int kLowRateFieldNumber = 17;
  ::PROTOBUF_NAMESPACE_ID::int64 lowrate() const;
  void set_lowrate(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 HtscVolume = 18;
  void clear_htscvolume();
  static const int kHtscVolumeFieldNumber = 18;
  ::PROTOBUF_NAMESPACE_ID::int64 htscvolume() const;
  void set_htscvolume(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 MarketVolume = 19;
  void clear_marketvolume();
  static const int kMarketVolumeFieldNumber = 19;
  ::PROTOBUF_NAMESPACE_ID::int64 marketvolume() const;
  void set_marketvolume(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 BestBorrowRate = 20;
  void clear_bestborrowrate();
  static const int kBestBorrowRateFieldNumber = 20;
  ::PROTOBUF_NAMESPACE_ID::int64 bestborrowrate() const;
  void set_bestborrowrate(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 BestLendRate = 21;
  void clear_bestlendrate();
  static const int kBestLendRateFieldNumber = 21;
  ::PROTOBUF_NAMESPACE_ID::int64 bestlendrate() const;
  void set_bestlendrate(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 BestReservationBorrowRate = 39;
  void clear_bestreservationborrowrate();
  static const int kBestReservationBorrowRateFieldNumber = 39;
  ::PROTOBUF_NAMESPACE_ID::int64 bestreservationborrowrate() const;
  void set_bestreservationborrowrate(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 BestReservationLendRate = 40;
  void clear_bestreservationlendrate();
  static const int kBestReservationLendRateFieldNumber = 40;
  ::PROTOBUF_NAMESPACE_ID::int64 bestreservationlendrate() const;
  void set_bestreservationlendrate(::PROTOBUF_NAMESPACE_ID::int64 value);

  // @@protoc_insertion_point(class_scope:com.htsc.mdc.insight.model.MDSecurityLending)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry > validborrows_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry > validalends_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry > validblends_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry > validclends_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry > alends_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry > blends_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry > clends_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry > validreservationborrows_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry > validreservationlends_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry > reservationborrows_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry > reservationlends_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry > validotclends_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr htscsecurityid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tradingphasecode_;
  ::PROTOBUF_NAMESPACE_ID::int32 mddate_;
  ::PROTOBUF_NAMESPACE_ID::int32 mdtime_;
  ::PROTOBUF_NAMESPACE_ID::int64 datatimestamp_;
  int securityidsource_;
  int securitytype_;
  ::PROTOBUF_NAMESPACE_ID::int64 preweightedrate_;
  ::PROTOBUF_NAMESPACE_ID::int64 prehighrate_;
  ::PROTOBUF_NAMESPACE_ID::int64 prelowrate_;
  ::PROTOBUF_NAMESPACE_ID::int64 prehtscvolume_;
  ::PROTOBUF_NAMESPACE_ID::int64 premarketvolume_;
  ::PROTOBUF_NAMESPACE_ID::int64 weightedrate_;
  ::PROTOBUF_NAMESPACE_ID::int64 highrate_;
  ::PROTOBUF_NAMESPACE_ID::int64 lowrate_;
  ::PROTOBUF_NAMESPACE_ID::int64 htscvolume_;
  ::PROTOBUF_NAMESPACE_ID::int64 marketvolume_;
  ::PROTOBUF_NAMESPACE_ID::int64 bestborrowrate_;
  ::PROTOBUF_NAMESPACE_ID::int64 bestlendrate_;
  ::PROTOBUF_NAMESPACE_ID::int64 bestreservationborrowrate_;
  ::PROTOBUF_NAMESPACE_ID::int64 bestreservationlendrate_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MDSecurityLending_2eproto;
};
// -------------------------------------------------------------------

class ADValidSecurityLendingEntry :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.htsc.mdc.insight.model.ADValidSecurityLendingEntry) */ {
 public:
  ADValidSecurityLendingEntry();
  virtual ~ADValidSecurityLendingEntry();

  ADValidSecurityLendingEntry(const ADValidSecurityLendingEntry& from);
  ADValidSecurityLendingEntry(ADValidSecurityLendingEntry&& from) noexcept
    : ADValidSecurityLendingEntry() {
    *this = ::std::move(from);
  }

  inline ADValidSecurityLendingEntry& operator=(const ADValidSecurityLendingEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline ADValidSecurityLendingEntry& operator=(ADValidSecurityLendingEntry&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ADValidSecurityLendingEntry& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ADValidSecurityLendingEntry* internal_default_instance() {
    return reinterpret_cast<const ADValidSecurityLendingEntry*>(
               &_ADValidSecurityLendingEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ADValidSecurityLendingEntry* other);
  friend void swap(ADValidSecurityLendingEntry& a, ADValidSecurityLendingEntry& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ADValidSecurityLendingEntry* New() const final {
    return CreateMaybeMessage<ADValidSecurityLendingEntry>(nullptr);
  }

  ADValidSecurityLendingEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ADValidSecurityLendingEntry>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ADValidSecurityLendingEntry& from);
  void MergeFrom(const ADValidSecurityLendingEntry& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ADValidSecurityLendingEntry* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.htsc.mdc.insight.model.ADValidSecurityLendingEntry";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MDSecurityLending_2eproto);
    return ::descriptor_table_MDSecurityLending_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 Rate = 2;
  void clear_rate();
  static const int kRateFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::int64 rate() const;
  void set_rate(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int32 Level = 1;
  void clear_level();
  static const int kLevelFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 level() const;
  void set_level(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 Term = 3;
  void clear_term();
  static const int kTermFieldNumber = 3;
  ::PROTOBUF_NAMESPACE_ID::int32 term() const;
  void set_term(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int64 Amount = 4;
  void clear_amount();
  static const int kAmountFieldNumber = 4;
  ::PROTOBUF_NAMESPACE_ID::int64 amount() const;
  void set_amount(::PROTOBUF_NAMESPACE_ID::int64 value);

  // bool HtscProvided = 5;
  void clear_htscprovided();
  static const int kHtscProvidedFieldNumber = 5;
  bool htscprovided() const;
  void set_htscprovided(bool value);

  // @@protoc_insertion_point(class_scope:com.htsc.mdc.insight.model.ADValidSecurityLendingEntry)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int64 rate_;
  ::PROTOBUF_NAMESPACE_ID::int32 level_;
  ::PROTOBUF_NAMESPACE_ID::int32 term_;
  ::PROTOBUF_NAMESPACE_ID::int64 amount_;
  bool htscprovided_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MDSecurityLending_2eproto;
};
// -------------------------------------------------------------------

class ADSecurityLendingEntry :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.htsc.mdc.insight.model.ADSecurityLendingEntry) */ {
 public:
  ADSecurityLendingEntry();
  virtual ~ADSecurityLendingEntry();

  ADSecurityLendingEntry(const ADSecurityLendingEntry& from);
  ADSecurityLendingEntry(ADSecurityLendingEntry&& from) noexcept
    : ADSecurityLendingEntry() {
    *this = ::std::move(from);
  }

  inline ADSecurityLendingEntry& operator=(const ADSecurityLendingEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline ADSecurityLendingEntry& operator=(ADSecurityLendingEntry&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ADSecurityLendingEntry& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ADSecurityLendingEntry* internal_default_instance() {
    return reinterpret_cast<const ADSecurityLendingEntry*>(
               &_ADSecurityLendingEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ADSecurityLendingEntry* other);
  friend void swap(ADSecurityLendingEntry& a, ADSecurityLendingEntry& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ADSecurityLendingEntry* New() const final {
    return CreateMaybeMessage<ADSecurityLendingEntry>(nullptr);
  }

  ADSecurityLendingEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ADSecurityLendingEntry>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ADSecurityLendingEntry& from);
  void MergeFrom(const ADSecurityLendingEntry& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ADSecurityLendingEntry* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.htsc.mdc.insight.model.ADSecurityLendingEntry";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MDSecurityLending_2eproto);
    return ::descriptor_table_MDSecurityLending_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 Rate = 2;
  void clear_rate();
  static const int kRateFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::int64 rate() const;
  void set_rate(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int32 Level = 1;
  void clear_level();
  static const int kLevelFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 level() const;
  void set_level(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 Term = 3;
  void clear_term();
  static const int kTermFieldNumber = 3;
  ::PROTOBUF_NAMESPACE_ID::int32 term() const;
  void set_term(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int64 TotalAmount = 4;
  void clear_totalamount();
  static const int kTotalAmountFieldNumber = 4;
  ::PROTOBUF_NAMESPACE_ID::int64 totalamount() const;
  void set_totalamount(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 MatchedAmount = 5;
  void clear_matchedamount();
  static const int kMatchedAmountFieldNumber = 5;
  ::PROTOBUF_NAMESPACE_ID::int64 matchedamount() const;
  void set_matchedamount(::PROTOBUF_NAMESPACE_ID::int64 value);

  // @@protoc_insertion_point(class_scope:com.htsc.mdc.insight.model.ADSecurityLendingEntry)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int64 rate_;
  ::PROTOBUF_NAMESPACE_ID::int32 level_;
  ::PROTOBUF_NAMESPACE_ID::int32 term_;
  ::PROTOBUF_NAMESPACE_ID::int64 totalamount_;
  ::PROTOBUF_NAMESPACE_ID::int64 matchedamount_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MDSecurityLending_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MDSecurityLending

// string HTSCSecurityID = 1;
inline void MDSecurityLending::clear_htscsecurityid() {
  htscsecurityid_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& MDSecurityLending::htscsecurityid() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.HTSCSecurityID)
  return htscsecurityid_.GetNoArena();
}
inline void MDSecurityLending::set_htscsecurityid(const std::string& value) {
  
  htscsecurityid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.HTSCSecurityID)
}
inline void MDSecurityLending::set_htscsecurityid(std::string&& value) {
  
  htscsecurityid_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.htsc.mdc.insight.model.MDSecurityLending.HTSCSecurityID)
}
inline void MDSecurityLending::set_htscsecurityid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  htscsecurityid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.htsc.mdc.insight.model.MDSecurityLending.HTSCSecurityID)
}
inline void MDSecurityLending::set_htscsecurityid(const char* value, size_t size) {
  
  htscsecurityid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.htsc.mdc.insight.model.MDSecurityLending.HTSCSecurityID)
}
inline std::string* MDSecurityLending::mutable_htscsecurityid() {
  
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDSecurityLending.HTSCSecurityID)
  return htscsecurityid_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MDSecurityLending::release_htscsecurityid() {
  // @@protoc_insertion_point(field_release:com.htsc.mdc.insight.model.MDSecurityLending.HTSCSecurityID)
  
  return htscsecurityid_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MDSecurityLending::set_allocated_htscsecurityid(std::string* htscsecurityid) {
  if (htscsecurityid != nullptr) {
    
  } else {
    
  }
  htscsecurityid_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), htscsecurityid);
  // @@protoc_insertion_point(field_set_allocated:com.htsc.mdc.insight.model.MDSecurityLending.HTSCSecurityID)
}

// int32 MDDate = 2;
inline void MDSecurityLending::clear_mddate() {
  mddate_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MDSecurityLending::mddate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.MDDate)
  return mddate_;
}
inline void MDSecurityLending::set_mddate(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  mddate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.MDDate)
}

// int32 MDTime = 3;
inline void MDSecurityLending::clear_mdtime() {
  mdtime_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MDSecurityLending::mdtime() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.MDTime)
  return mdtime_;
}
inline void MDSecurityLending::set_mdtime(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  mdtime_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.MDTime)
}

// int64 DataTimestamp = 4;
inline void MDSecurityLending::clear_datatimestamp() {
  datatimestamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::datatimestamp() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.DataTimestamp)
  return datatimestamp_;
}
inline void MDSecurityLending::set_datatimestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  datatimestamp_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.DataTimestamp)
}

// string TradingPhaseCode = 5;
inline void MDSecurityLending::clear_tradingphasecode() {
  tradingphasecode_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& MDSecurityLending::tradingphasecode() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.TradingPhaseCode)
  return tradingphasecode_.GetNoArena();
}
inline void MDSecurityLending::set_tradingphasecode(const std::string& value) {
  
  tradingphasecode_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.TradingPhaseCode)
}
inline void MDSecurityLending::set_tradingphasecode(std::string&& value) {
  
  tradingphasecode_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.htsc.mdc.insight.model.MDSecurityLending.TradingPhaseCode)
}
inline void MDSecurityLending::set_tradingphasecode(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  tradingphasecode_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.htsc.mdc.insight.model.MDSecurityLending.TradingPhaseCode)
}
inline void MDSecurityLending::set_tradingphasecode(const char* value, size_t size) {
  
  tradingphasecode_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.htsc.mdc.insight.model.MDSecurityLending.TradingPhaseCode)
}
inline std::string* MDSecurityLending::mutable_tradingphasecode() {
  
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDSecurityLending.TradingPhaseCode)
  return tradingphasecode_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MDSecurityLending::release_tradingphasecode() {
  // @@protoc_insertion_point(field_release:com.htsc.mdc.insight.model.MDSecurityLending.TradingPhaseCode)
  
  return tradingphasecode_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MDSecurityLending::set_allocated_tradingphasecode(std::string* tradingphasecode) {
  if (tradingphasecode != nullptr) {
    
  } else {
    
  }
  tradingphasecode_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), tradingphasecode);
  // @@protoc_insertion_point(field_set_allocated:com.htsc.mdc.insight.model.MDSecurityLending.TradingPhaseCode)
}

// .com.htsc.mdc.model.ESecurityIDSource securityIDSource = 6;
inline void MDSecurityLending::clear_securityidsource() {
  securityidsource_ = 0;
}
inline ::com::htsc::mdc::model::ESecurityIDSource MDSecurityLending::securityidsource() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.securityIDSource)
  return static_cast< ::com::htsc::mdc::model::ESecurityIDSource >(securityidsource_);
}
inline void MDSecurityLending::set_securityidsource(::com::htsc::mdc::model::ESecurityIDSource value) {
  
  securityidsource_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.securityIDSource)
}

// .com.htsc.mdc.model.ESecurityType securityType = 7;
inline void MDSecurityLending::clear_securitytype() {
  securitytype_ = 0;
}
inline ::com::htsc::mdc::model::ESecurityType MDSecurityLending::securitytype() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.securityType)
  return static_cast< ::com::htsc::mdc::model::ESecurityType >(securitytype_);
}
inline void MDSecurityLending::set_securitytype(::com::htsc::mdc::model::ESecurityType value) {
  
  securitytype_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.securityType)
}

// int64 PreWeightedRate = 10;
inline void MDSecurityLending::clear_preweightedrate() {
  preweightedrate_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::preweightedrate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.PreWeightedRate)
  return preweightedrate_;
}
inline void MDSecurityLending::set_preweightedrate(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  preweightedrate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.PreWeightedRate)
}

// int64 PreHighRate = 11;
inline void MDSecurityLending::clear_prehighrate() {
  prehighrate_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::prehighrate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.PreHighRate)
  return prehighrate_;
}
inline void MDSecurityLending::set_prehighrate(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  prehighrate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.PreHighRate)
}

// int64 PreLowRate = 12;
inline void MDSecurityLending::clear_prelowrate() {
  prelowrate_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::prelowrate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.PreLowRate)
  return prelowrate_;
}
inline void MDSecurityLending::set_prelowrate(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  prelowrate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.PreLowRate)
}

// int64 PreHtscVolume = 13;
inline void MDSecurityLending::clear_prehtscvolume() {
  prehtscvolume_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::prehtscvolume() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.PreHtscVolume)
  return prehtscvolume_;
}
inline void MDSecurityLending::set_prehtscvolume(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  prehtscvolume_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.PreHtscVolume)
}

// int64 PreMarketVolume = 14;
inline void MDSecurityLending::clear_premarketvolume() {
  premarketvolume_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::premarketvolume() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.PreMarketVolume)
  return premarketvolume_;
}
inline void MDSecurityLending::set_premarketvolume(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  premarketvolume_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.PreMarketVolume)
}

// int64 WeightedRate = 15;
inline void MDSecurityLending::clear_weightedrate() {
  weightedrate_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::weightedrate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.WeightedRate)
  return weightedrate_;
}
inline void MDSecurityLending::set_weightedrate(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  weightedrate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.WeightedRate)
}

// int64 HighRate = 16;
inline void MDSecurityLending::clear_highrate() {
  highrate_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::highrate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.HighRate)
  return highrate_;
}
inline void MDSecurityLending::set_highrate(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  highrate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.HighRate)
}

// int64 LowRate = 17;
inline void MDSecurityLending::clear_lowrate() {
  lowrate_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::lowrate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.LowRate)
  return lowrate_;
}
inline void MDSecurityLending::set_lowrate(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  lowrate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.LowRate)
}

// int64 HtscVolume = 18;
inline void MDSecurityLending::clear_htscvolume() {
  htscvolume_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::htscvolume() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.HtscVolume)
  return htscvolume_;
}
inline void MDSecurityLending::set_htscvolume(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  htscvolume_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.HtscVolume)
}

// int64 MarketVolume = 19;
inline void MDSecurityLending::clear_marketvolume() {
  marketvolume_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::marketvolume() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.MarketVolume)
  return marketvolume_;
}
inline void MDSecurityLending::set_marketvolume(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  marketvolume_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.MarketVolume)
}

// int64 BestBorrowRate = 20;
inline void MDSecurityLending::clear_bestborrowrate() {
  bestborrowrate_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::bestborrowrate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.BestBorrowRate)
  return bestborrowrate_;
}
inline void MDSecurityLending::set_bestborrowrate(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  bestborrowrate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.BestBorrowRate)
}

// int64 BestLendRate = 21;
inline void MDSecurityLending::clear_bestlendrate() {
  bestlendrate_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::bestlendrate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.BestLendRate)
  return bestlendrate_;
}
inline void MDSecurityLending::set_bestlendrate(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  bestlendrate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.BestLendRate)
}

// repeated .com.htsc.mdc.insight.model.ADValidSecurityLendingEntry ValidBorrows = 27;
inline int MDSecurityLending::validborrows_size() const {
  return validborrows_.size();
}
inline void MDSecurityLending::clear_validborrows() {
  validborrows_.Clear();
}
inline ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* MDSecurityLending::mutable_validborrows(int index) {
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDSecurityLending.ValidBorrows)
  return validborrows_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >*
MDSecurityLending::mutable_validborrows() {
  // @@protoc_insertion_point(field_mutable_list:com.htsc.mdc.insight.model.MDSecurityLending.ValidBorrows)
  return &validborrows_;
}
inline const ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry& MDSecurityLending::validborrows(int index) const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.ValidBorrows)
  return validborrows_.Get(index);
}
inline ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* MDSecurityLending::add_validborrows() {
  // @@protoc_insertion_point(field_add:com.htsc.mdc.insight.model.MDSecurityLending.ValidBorrows)
  return validborrows_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >&
MDSecurityLending::validborrows() const {
  // @@protoc_insertion_point(field_list:com.htsc.mdc.insight.model.MDSecurityLending.ValidBorrows)
  return validborrows_;
}

// repeated .com.htsc.mdc.insight.model.ADValidSecurityLendingEntry ValidALends = 28;
inline int MDSecurityLending::validalends_size() const {
  return validalends_.size();
}
inline void MDSecurityLending::clear_validalends() {
  validalends_.Clear();
}
inline ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* MDSecurityLending::mutable_validalends(int index) {
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDSecurityLending.ValidALends)
  return validalends_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >*
MDSecurityLending::mutable_validalends() {
  // @@protoc_insertion_point(field_mutable_list:com.htsc.mdc.insight.model.MDSecurityLending.ValidALends)
  return &validalends_;
}
inline const ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry& MDSecurityLending::validalends(int index) const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.ValidALends)
  return validalends_.Get(index);
}
inline ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* MDSecurityLending::add_validalends() {
  // @@protoc_insertion_point(field_add:com.htsc.mdc.insight.model.MDSecurityLending.ValidALends)
  return validalends_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >&
MDSecurityLending::validalends() const {
  // @@protoc_insertion_point(field_list:com.htsc.mdc.insight.model.MDSecurityLending.ValidALends)
  return validalends_;
}

// repeated .com.htsc.mdc.insight.model.ADValidSecurityLendingEntry ValidBLends = 29;
inline int MDSecurityLending::validblends_size() const {
  return validblends_.size();
}
inline void MDSecurityLending::clear_validblends() {
  validblends_.Clear();
}
inline ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* MDSecurityLending::mutable_validblends(int index) {
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDSecurityLending.ValidBLends)
  return validblends_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >*
MDSecurityLending::mutable_validblends() {
  // @@protoc_insertion_point(field_mutable_list:com.htsc.mdc.insight.model.MDSecurityLending.ValidBLends)
  return &validblends_;
}
inline const ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry& MDSecurityLending::validblends(int index) const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.ValidBLends)
  return validblends_.Get(index);
}
inline ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* MDSecurityLending::add_validblends() {
  // @@protoc_insertion_point(field_add:com.htsc.mdc.insight.model.MDSecurityLending.ValidBLends)
  return validblends_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >&
MDSecurityLending::validblends() const {
  // @@protoc_insertion_point(field_list:com.htsc.mdc.insight.model.MDSecurityLending.ValidBLends)
  return validblends_;
}

// repeated .com.htsc.mdc.insight.model.ADValidSecurityLendingEntry ValidCLends = 30;
inline int MDSecurityLending::validclends_size() const {
  return validclends_.size();
}
inline void MDSecurityLending::clear_validclends() {
  validclends_.Clear();
}
inline ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* MDSecurityLending::mutable_validclends(int index) {
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDSecurityLending.ValidCLends)
  return validclends_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >*
MDSecurityLending::mutable_validclends() {
  // @@protoc_insertion_point(field_mutable_list:com.htsc.mdc.insight.model.MDSecurityLending.ValidCLends)
  return &validclends_;
}
inline const ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry& MDSecurityLending::validclends(int index) const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.ValidCLends)
  return validclends_.Get(index);
}
inline ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* MDSecurityLending::add_validclends() {
  // @@protoc_insertion_point(field_add:com.htsc.mdc.insight.model.MDSecurityLending.ValidCLends)
  return validclends_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >&
MDSecurityLending::validclends() const {
  // @@protoc_insertion_point(field_list:com.htsc.mdc.insight.model.MDSecurityLending.ValidCLends)
  return validclends_;
}

// repeated .com.htsc.mdc.insight.model.ADSecurityLendingEntry ALends = 31;
inline int MDSecurityLending::alends_size() const {
  return alends_.size();
}
inline void MDSecurityLending::clear_alends() {
  alends_.Clear();
}
inline ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* MDSecurityLending::mutable_alends(int index) {
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDSecurityLending.ALends)
  return alends_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >*
MDSecurityLending::mutable_alends() {
  // @@protoc_insertion_point(field_mutable_list:com.htsc.mdc.insight.model.MDSecurityLending.ALends)
  return &alends_;
}
inline const ::com::htsc::mdc::insight::model::ADSecurityLendingEntry& MDSecurityLending::alends(int index) const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.ALends)
  return alends_.Get(index);
}
inline ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* MDSecurityLending::add_alends() {
  // @@protoc_insertion_point(field_add:com.htsc.mdc.insight.model.MDSecurityLending.ALends)
  return alends_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >&
MDSecurityLending::alends() const {
  // @@protoc_insertion_point(field_list:com.htsc.mdc.insight.model.MDSecurityLending.ALends)
  return alends_;
}

// repeated .com.htsc.mdc.insight.model.ADSecurityLendingEntry BLends = 32;
inline int MDSecurityLending::blends_size() const {
  return blends_.size();
}
inline void MDSecurityLending::clear_blends() {
  blends_.Clear();
}
inline ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* MDSecurityLending::mutable_blends(int index) {
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDSecurityLending.BLends)
  return blends_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >*
MDSecurityLending::mutable_blends() {
  // @@protoc_insertion_point(field_mutable_list:com.htsc.mdc.insight.model.MDSecurityLending.BLends)
  return &blends_;
}
inline const ::com::htsc::mdc::insight::model::ADSecurityLendingEntry& MDSecurityLending::blends(int index) const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.BLends)
  return blends_.Get(index);
}
inline ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* MDSecurityLending::add_blends() {
  // @@protoc_insertion_point(field_add:com.htsc.mdc.insight.model.MDSecurityLending.BLends)
  return blends_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >&
MDSecurityLending::blends() const {
  // @@protoc_insertion_point(field_list:com.htsc.mdc.insight.model.MDSecurityLending.BLends)
  return blends_;
}

// repeated .com.htsc.mdc.insight.model.ADSecurityLendingEntry CLends = 33;
inline int MDSecurityLending::clends_size() const {
  return clends_.size();
}
inline void MDSecurityLending::clear_clends() {
  clends_.Clear();
}
inline ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* MDSecurityLending::mutable_clends(int index) {
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDSecurityLending.CLends)
  return clends_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >*
MDSecurityLending::mutable_clends() {
  // @@protoc_insertion_point(field_mutable_list:com.htsc.mdc.insight.model.MDSecurityLending.CLends)
  return &clends_;
}
inline const ::com::htsc::mdc::insight::model::ADSecurityLendingEntry& MDSecurityLending::clends(int index) const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.CLends)
  return clends_.Get(index);
}
inline ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* MDSecurityLending::add_clends() {
  // @@protoc_insertion_point(field_add:com.htsc.mdc.insight.model.MDSecurityLending.CLends)
  return clends_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >&
MDSecurityLending::clends() const {
  // @@protoc_insertion_point(field_list:com.htsc.mdc.insight.model.MDSecurityLending.CLends)
  return clends_;
}

// repeated .com.htsc.mdc.insight.model.ADValidSecurityLendingEntry ValidReservationBorrows = 34;
inline int MDSecurityLending::validreservationborrows_size() const {
  return validreservationborrows_.size();
}
inline void MDSecurityLending::clear_validreservationborrows() {
  validreservationborrows_.Clear();
}
inline ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* MDSecurityLending::mutable_validreservationborrows(int index) {
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDSecurityLending.ValidReservationBorrows)
  return validreservationborrows_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >*
MDSecurityLending::mutable_validreservationborrows() {
  // @@protoc_insertion_point(field_mutable_list:com.htsc.mdc.insight.model.MDSecurityLending.ValidReservationBorrows)
  return &validreservationborrows_;
}
inline const ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry& MDSecurityLending::validreservationborrows(int index) const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.ValidReservationBorrows)
  return validreservationborrows_.Get(index);
}
inline ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* MDSecurityLending::add_validreservationborrows() {
  // @@protoc_insertion_point(field_add:com.htsc.mdc.insight.model.MDSecurityLending.ValidReservationBorrows)
  return validreservationborrows_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >&
MDSecurityLending::validreservationborrows() const {
  // @@protoc_insertion_point(field_list:com.htsc.mdc.insight.model.MDSecurityLending.ValidReservationBorrows)
  return validreservationborrows_;
}

// repeated .com.htsc.mdc.insight.model.ADValidSecurityLendingEntry ValidReservationLends = 35;
inline int MDSecurityLending::validreservationlends_size() const {
  return validreservationlends_.size();
}
inline void MDSecurityLending::clear_validreservationlends() {
  validreservationlends_.Clear();
}
inline ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* MDSecurityLending::mutable_validreservationlends(int index) {
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDSecurityLending.ValidReservationLends)
  return validreservationlends_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >*
MDSecurityLending::mutable_validreservationlends() {
  // @@protoc_insertion_point(field_mutable_list:com.htsc.mdc.insight.model.MDSecurityLending.ValidReservationLends)
  return &validreservationlends_;
}
inline const ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry& MDSecurityLending::validreservationlends(int index) const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.ValidReservationLends)
  return validreservationlends_.Get(index);
}
inline ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* MDSecurityLending::add_validreservationlends() {
  // @@protoc_insertion_point(field_add:com.htsc.mdc.insight.model.MDSecurityLending.ValidReservationLends)
  return validreservationlends_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >&
MDSecurityLending::validreservationlends() const {
  // @@protoc_insertion_point(field_list:com.htsc.mdc.insight.model.MDSecurityLending.ValidReservationLends)
  return validreservationlends_;
}

// repeated .com.htsc.mdc.insight.model.ADSecurityLendingEntry ReservationBorrows = 36;
inline int MDSecurityLending::reservationborrows_size() const {
  return reservationborrows_.size();
}
inline void MDSecurityLending::clear_reservationborrows() {
  reservationborrows_.Clear();
}
inline ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* MDSecurityLending::mutable_reservationborrows(int index) {
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDSecurityLending.ReservationBorrows)
  return reservationborrows_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >*
MDSecurityLending::mutable_reservationborrows() {
  // @@protoc_insertion_point(field_mutable_list:com.htsc.mdc.insight.model.MDSecurityLending.ReservationBorrows)
  return &reservationborrows_;
}
inline const ::com::htsc::mdc::insight::model::ADSecurityLendingEntry& MDSecurityLending::reservationborrows(int index) const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.ReservationBorrows)
  return reservationborrows_.Get(index);
}
inline ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* MDSecurityLending::add_reservationborrows() {
  // @@protoc_insertion_point(field_add:com.htsc.mdc.insight.model.MDSecurityLending.ReservationBorrows)
  return reservationborrows_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >&
MDSecurityLending::reservationborrows() const {
  // @@protoc_insertion_point(field_list:com.htsc.mdc.insight.model.MDSecurityLending.ReservationBorrows)
  return reservationborrows_;
}

// repeated .com.htsc.mdc.insight.model.ADSecurityLendingEntry ReservationLends = 37;
inline int MDSecurityLending::reservationlends_size() const {
  return reservationlends_.size();
}
inline void MDSecurityLending::clear_reservationlends() {
  reservationlends_.Clear();
}
inline ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* MDSecurityLending::mutable_reservationlends(int index) {
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDSecurityLending.ReservationLends)
  return reservationlends_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >*
MDSecurityLending::mutable_reservationlends() {
  // @@protoc_insertion_point(field_mutable_list:com.htsc.mdc.insight.model.MDSecurityLending.ReservationLends)
  return &reservationlends_;
}
inline const ::com::htsc::mdc::insight::model::ADSecurityLendingEntry& MDSecurityLending::reservationlends(int index) const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.ReservationLends)
  return reservationlends_.Get(index);
}
inline ::com::htsc::mdc::insight::model::ADSecurityLendingEntry* MDSecurityLending::add_reservationlends() {
  // @@protoc_insertion_point(field_add:com.htsc.mdc.insight.model.MDSecurityLending.ReservationLends)
  return reservationlends_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADSecurityLendingEntry >&
MDSecurityLending::reservationlends() const {
  // @@protoc_insertion_point(field_list:com.htsc.mdc.insight.model.MDSecurityLending.ReservationLends)
  return reservationlends_;
}

// repeated .com.htsc.mdc.insight.model.ADValidSecurityLendingEntry ValidOtcLends = 38;
inline int MDSecurityLending::validotclends_size() const {
  return validotclends_.size();
}
inline void MDSecurityLending::clear_validotclends() {
  validotclends_.Clear();
}
inline ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* MDSecurityLending::mutable_validotclends(int index) {
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDSecurityLending.ValidOtcLends)
  return validotclends_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >*
MDSecurityLending::mutable_validotclends() {
  // @@protoc_insertion_point(field_mutable_list:com.htsc.mdc.insight.model.MDSecurityLending.ValidOtcLends)
  return &validotclends_;
}
inline const ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry& MDSecurityLending::validotclends(int index) const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.ValidOtcLends)
  return validotclends_.Get(index);
}
inline ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry* MDSecurityLending::add_validotclends() {
  // @@protoc_insertion_point(field_add:com.htsc.mdc.insight.model.MDSecurityLending.ValidOtcLends)
  return validotclends_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::com::htsc::mdc::insight::model::ADValidSecurityLendingEntry >&
MDSecurityLending::validotclends() const {
  // @@protoc_insertion_point(field_list:com.htsc.mdc.insight.model.MDSecurityLending.ValidOtcLends)
  return validotclends_;
}

// int64 BestReservationBorrowRate = 39;
inline void MDSecurityLending::clear_bestreservationborrowrate() {
  bestreservationborrowrate_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::bestreservationborrowrate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.BestReservationBorrowRate)
  return bestreservationborrowrate_;
}
inline void MDSecurityLending::set_bestreservationborrowrate(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  bestreservationborrowrate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.BestReservationBorrowRate)
}

// int64 BestReservationLendRate = 40;
inline void MDSecurityLending::clear_bestreservationlendrate() {
  bestreservationlendrate_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDSecurityLending::bestreservationlendrate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDSecurityLending.BestReservationLendRate)
  return bestreservationlendrate_;
}
inline void MDSecurityLending::set_bestreservationlendrate(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  bestreservationlendrate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDSecurityLending.BestReservationLendRate)
}

// -------------------------------------------------------------------

// ADValidSecurityLendingEntry

// int32 Level = 1;
inline void ADValidSecurityLendingEntry::clear_level() {
  level_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ADValidSecurityLendingEntry::level() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.ADValidSecurityLendingEntry.Level)
  return level_;
}
inline void ADValidSecurityLendingEntry::set_level(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.ADValidSecurityLendingEntry.Level)
}

// int64 Rate = 2;
inline void ADValidSecurityLendingEntry::clear_rate() {
  rate_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ADValidSecurityLendingEntry::rate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.ADValidSecurityLendingEntry.Rate)
  return rate_;
}
inline void ADValidSecurityLendingEntry::set_rate(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  rate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.ADValidSecurityLendingEntry.Rate)
}

// int32 Term = 3;
inline void ADValidSecurityLendingEntry::clear_term() {
  term_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ADValidSecurityLendingEntry::term() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.ADValidSecurityLendingEntry.Term)
  return term_;
}
inline void ADValidSecurityLendingEntry::set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.ADValidSecurityLendingEntry.Term)
}

// int64 Amount = 4;
inline void ADValidSecurityLendingEntry::clear_amount() {
  amount_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ADValidSecurityLendingEntry::amount() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.ADValidSecurityLendingEntry.Amount)
  return amount_;
}
inline void ADValidSecurityLendingEntry::set_amount(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  amount_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.ADValidSecurityLendingEntry.Amount)
}

// bool HtscProvided = 5;
inline void ADValidSecurityLendingEntry::clear_htscprovided() {
  htscprovided_ = false;
}
inline bool ADValidSecurityLendingEntry::htscprovided() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.ADValidSecurityLendingEntry.HtscProvided)
  return htscprovided_;
}
inline void ADValidSecurityLendingEntry::set_htscprovided(bool value) {
  
  htscprovided_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.ADValidSecurityLendingEntry.HtscProvided)
}

// -------------------------------------------------------------------

// ADSecurityLendingEntry

// int32 Level = 1;
inline void ADSecurityLendingEntry::clear_level() {
  level_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ADSecurityLendingEntry::level() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.ADSecurityLendingEntry.Level)
  return level_;
}
inline void ADSecurityLendingEntry::set_level(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.ADSecurityLendingEntry.Level)
}

// int64 Rate = 2;
inline void ADSecurityLendingEntry::clear_rate() {
  rate_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ADSecurityLendingEntry::rate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.ADSecurityLendingEntry.Rate)
  return rate_;
}
inline void ADSecurityLendingEntry::set_rate(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  rate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.ADSecurityLendingEntry.Rate)
}

// int32 Term = 3;
inline void ADSecurityLendingEntry::clear_term() {
  term_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ADSecurityLendingEntry::term() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.ADSecurityLendingEntry.Term)
  return term_;
}
inline void ADSecurityLendingEntry::set_term(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.ADSecurityLendingEntry.Term)
}

// int64 TotalAmount = 4;
inline void ADSecurityLendingEntry::clear_totalamount() {
  totalamount_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ADSecurityLendingEntry::totalamount() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.ADSecurityLendingEntry.TotalAmount)
  return totalamount_;
}
inline void ADSecurityLendingEntry::set_totalamount(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  totalamount_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.ADSecurityLendingEntry.TotalAmount)
}

// int64 MatchedAmount = 5;
inline void ADSecurityLendingEntry::clear_matchedamount() {
  matchedamount_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ADSecurityLendingEntry::matchedamount() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.ADSecurityLendingEntry.MatchedAmount)
  return matchedamount_;
}
inline void ADSecurityLendingEntry::set_matchedamount(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  matchedamount_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.ADSecurityLendingEntry.MatchedAmount)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace model
}  // namespace insight
}  // namespace mdc
}  // namespace htsc
}  // namespace com

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MDSecurityLending_2eproto
